### ISSUE TITLE
能否支持ipv6

### ISSUE THREAD

**Issue by dxxzst** [helloxz/docker-transmission#1]
在纯ipv6的机器上安装了，试着下载不了，能否支持一下

**Comment by helloxz** [comment]
是docker镜像拉取不下来还是什么情况呢，能详细说明下吗？

**Comment by dxxzst** [comment]
下载没有速度，试了好几个资源都是这样。应该是transmission的问题

**Comment by dxxzst** [comment]
IP4的机器上都正常，多谢
