### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by HumgTop** [helloxz/docker-transmission#2]
你好，请问原生的/config 和 /watch目录对应的路径是什么？还有镜像里没有安装bash吗？

**Comment by helloxz** [comment]
1. 路径位于`/root/.config/transmission-daemon/`
2. 为了缩小体积，是用的Alpine作为基础镜像，不支持bash，请使用`sh`进入容器

**Comment by helloxz** [comment]
docker exec -it container_id /bin/sh

**Comment by HumgTop** [comment]
> 1. 路径位于`/root/.config/transmission-daemon/`
> 2. 为了缩小体积，是用的Alpine作为基础镜像，不支持bash，请使用`sh`进入容器:
> 
> ```shell
> docker exec -it container_id /bin/sh
> ```

好的已解决，感谢大佬！
