### ISSUE TITLE
远程访问web ui失败

### ISSUE THREAD

**Issue by venpong** [helloxz/docker-transmission#3]
环境:centos7+docker+路由器(openwrt)转发9091、51413端口+f3322动态域名
问题描述：使用脚本安装完transmission之后，访问f3322+9091,显示403，故修改setting.json关闭ip白名单后(将rpc-whitelist-enabled改成false)能成功进入UI页面，但是UI页面无法显示完整且无法连接transmission服务器，浏览器控制台报错
![image](https://user-images.githubusercontent.com/14030911/112255567-6cea9880-8c9d-11eb-9a0f-de90f0055169.png)

**Comment by helloxz** [comment]
f3322是什么情况？不是应该映射9091和51413么，把运行参数和你完整映射关系发出来看下。

**Comment by venpong** [comment]
![image](https://user-images.githubusercontent.com/14030911/112262277-61e93580-8ca8-11eb-8c5e-db7fcb91c327.png)
![image](https://user-images.githubusercontent.com/14030911/112262475-ad034880-8ca8-11eb-89b6-5248ef61e013.png)

是路由器使用了f3322动态域名解析，然后路由器下面挂了centos服务器，centos服务器上的docker安装了transmission,然后访问webui就是f3322的域名+9091端口

**Comment by helloxz** [comment]
你映射完毕后首先在内外测试是否访问正常，如果内外访问OK的，说明服务没问题。然后通过telnet外网端口开是否正常，如果不正常，则外网映射可能出了问题。

**Comment by venpong** [comment]
嗯嗯，没折腾了，在你博客看到了qbittorrent的教程，装完能用，就没弄transmission了。
